---
title: "R Notebook"
output: html_notebook
---
Import stuff
```{r}
require(readr)
require(lubridate)
require(hms)
require(dplyr)
require(ggplot2)
require(gridExtra)
```

```{r}
base_path <- "~/dev/coursera/google_analytics/08_capstone/bike_share/"
filename <- "Divvy_Trips_2019_Q"
bike_shares_2019_Q1 <- read_csv("~/dev/coursera/google_analytics/08_capstone/bike_share/Divvy_Trips_2019_Q1.zip")
bike_shares_2020_Q1 <- read_csv("~/dev/coursera/google_analytics/08_capstone/bike_share/Divvy_Trips_2020_Q1.zip")
# bike_shares <- merge(bike_shares_2019_Q1, bike_shares_2020_Q1)
```
Since we cannot allocate a dataframe containing data from 2019 and 2020 we're going to analyze them individually

### Process

```{r}
bike_shares_2019_Q1$ride_length <- as.hms(bike_shares_2019_Q1$end_time - bike_shares_2019_Q1$start_time)
bike_shares_2019_Q1$day_of_week <- as.POSIXlt(bike_shares_2019_Q1$end_time)$wday + 1
bike_shares_2019_Q1$start_hour <- as.hms(bike_shares_2019_Q1$start_time + hours(3))
head(bike_shares_2019_Q1[, c("start_time", "start_hour", "end_time", "ride_length", "day_of_week")])
```

```{r}
df$ride_length_mean <- as.hms(mean(bike_shares_2019_Q1$ride_length))
df$ride_length_max <- as.hms(max(bike_shares_2019_Q1$ride_length))
df$dow_mode <- names(which.max(table(bike_shares_2019_Q1$day_of_week)))[1]
head(df)
```


### Analyse

```{r}
agg_data <- bike_shares_2019_Q1 %>%
  group_by(usertype) %>%
  summarise(mean_ride_length = as.hms(mean(ride_length)))
print(agg_data)
```
```{r}
agg_data <- bike_shares_2019_Q1 %>%
  group_by(usertype, day_of_week) %>%
  summarise(mean_ride_length = as.hms(mean(ride_length)))
print(agg_data)
```

```{r}
agg_data <- bike_shares_2019_Q1 %>%
  group_by(trip_id) %>%
  summarise(trip_cnt = n()) %>%
  arrange(desc(trip_cnt))
head(agg_data)
```

trip_id's are unique

```{r}
by_day_of_wk <- bike_shares_2019_Q1 %>%
  group_by(day_of_week, usertype) %>%
  summarise(trip_cnt = n())
head(by_day_of_wk)
```


```{r}
ggplot(by_day_of_wk, aes(x=day_of_week, y=trip_cnt, fill=usertype)) + 
  geom_bar(stat="identity", position=position_dodge())
```

### Distribution of rides per daily hours

```{r}
customers_plot <- bike_shares_2019_Q1 %>% 
  filter(usertype=="Customer") %>% 
  # ggplot(bike_shares_2019_Q1, aes(x=start_hour, fill= usertype)) +
  ggplot(aes(x=start_hour)) +
    geom_histogram(bins=24) + 
    scale_x_time(breaks = seq(0, 3600*24, by=3600*4)) +
    labs(title="Distribution of customer rides per daily hour",
       x = "Hour of the Day",
       y = "Number of rides"
    )

subscribers_plot <- bike_shares_2019_Q1 %>% 
  filter(usertype=="Subscriber") %>% 
  ggplot(aes(x=start_hour)) +
    geom_histogram(bins=24) + 
    scale_x_time(breaks = seq(0, 3600*24, by=3600*4)) +
    labs(title="Distribution of subscriber rides per daily hour",
       x = "Hour of the Day",
       y = "Number of rides"
    )
grid.arrange(customers_plot, subscribers_plot, ncol=1)

```

## 2020 Q1

```{r}
glimpse(bike_shares_2020_Q1)
```


```{r}
bike_shares_2020_Q1$ride_length <- as.hms(bike_shares_2020_Q1$ended_at - bike_shares_2020_Q1$started_at)
bike_shares_2020_Q1$day_of_week <- as.POSIXlt(bike_shares_2020_Q1$ended_at)$wday + 1
bike_shares_2020_Q1$start_hour <- as.hms(bike_shares_2020_Q1$started_at + hours(3))
head(bike_shares_2020_Q1[, c("started_at", "start_hour", "ended_at", "ride_length", "day_of_week")])
```

### Analyse

```{r}
agg_data <- bike_shares_2020_Q1 %>%
  group_by(member_casual) %>%
  summarise(mean_ride_length = as.hms(mean(ride_length)))
print(agg_data)
```

```{r}
agg_data <- bike_shares_2020_Q1 %>%
  group_by(member_casual, day_of_week) %>%
  summarise(mean_ride_length = as.hms(mean(ride_length)))
print(agg_data)
```

```{r}
agg_data <- bike_shares_2020_Q1 %>%
  group_by(ride_id) %>%
  summarise(trip_cnt = n()) %>%
  arrange(desc(trip_cnt))
head(agg_data)
```

ride_id's are unique too


```{r}
by_day_of_wk <- bike_shares_2020_Q1 %>%
  group_by(day_of_week, member_casual) %>%
  summarise(trip_cnt = n())
head(by_day_of_wk)
```

```{r}
ggplot(by_day_of_wk, aes(x=day_of_week, y=trip_cnt, fill=member_casual)) + 
  geom_bar(stat="identity", position=position_dodge())
```




### Rides distribution among user categories

```{r}
customers_plot <- bike_shares_2020_Q1 %>% 
  filter(member_casual=="member") %>% 
  # ggplot(bike_shares_2019_Q1, aes(x=start_hour, fill= usertype)) +
  ggplot(aes(x=start_hour)) +
    geom_histogram(bins=24) + 
    scale_x_time(breaks = seq(0, 3600*24, by=3600*4)) +
    labs(title="Distribution of customer rides per daily hour",
       x = "Hour of the Day",
       y = "Number of rides"
    )

subscribers_plot <- bike_shares_2020_Q1 %>% 
  filter(member_casual=="casual") %>% 
  ggplot(aes(x=start_hour)) +
    geom_histogram(bins=24) + 
    scale_x_time(breaks = seq(0, 3600*24, by=3600*4)) +
    labs(title="Distribution of subscriber rides per daily hour",
       x = "Hour of the Day",
       y = "Number of rides"
    )
grid.arrange(customers_plot, subscribers_plot, ncol=1)
```
```{r}
max(bike_shares_2020_Q1$started_at)
```

